# Generated by Django 3.2.10 on 2021-12-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlearning', '0003_auto_20211229_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feactured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
