# Generated by Django 3.2.10 on 2022-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlearning', '0004_project_feactured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feactured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
